# Generated by Django 4.2.17 on 2024-12-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='material_images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='guide.era')),
            ],
        ),
    ]
