# Generated by Django 5.2.1 on 2025-05-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['era', 'order']},
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='mini_game_completed',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='era',
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='guide.lecture'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('era', 'order')},
        ),
        migrations.CreateModel(
            name='MiniGameUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.era')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'era')},
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
