# Generated by Django 4.2.17 on 2024-12-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='reward_xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
