# Generated by Django 4.2.17 on 2025-01-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completed_quests',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
