# Generated by Django 4.2.17 on 2025-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_remove_userprofile_completed_quests_delete_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='era',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
