# Generated by Django 4.2.17 on 2025-01-08 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_alter_era_image_alter_era_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/materials/'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='guide.era')),
            ],
        ),
    ]
