# Generated by Django 4.2.17 on 2025-01-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_remove_material_video_url_alter_material_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_4',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
