# Generated by Django 4.2.17 on 2025-01-09 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0010_remove_quizquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, to='guide.era'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
